apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: spring-boot-web-jsp
  name: spring-boot-web-jsp
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: spring-boot-web-jsp:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: amazoncorretto:8
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 7-VYPONtJiklkdMviYg7
    type: GitHub
  - generic:
      secret: aJPCfBOXuG3T6R3vF6Rg
    type: Generic
status:
  lastVersion: 0
