apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: spring-boot-web-jsp
  name: spring-boot-web-jsp
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: spring-boot-web-jsp
    deploymentconfig: spring-boot-web-jsp
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: spring-boot-web-jsp
        deploymentconfig: spring-boot-web-jsp
    spec:
      containers:
      - image: 172.30.37.22:5000/pccorp-esales-dev-axa-be/spring-boot-web-jsp@sha256:844f0118940e92f9e061f229c28013a2f31fcb0c13b7c50921faa528d6244a06
        imagePullPolicy: Always
        name: spring-boot-web-jsp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot-web-jsp
      from:
        kind: ImageStreamTag
        name: spring-boot-web-jsp:latest
        namespace: pccorp-esales-dev-axa-be
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
