apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-web-jsp
  name: spring-boot-web-jsp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-web-jsp
    deploymentconfig: spring-boot-web-jsp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
